### ISSUE TITLE
Set/Map monoids

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SteveGilham/fsharp-typeclasses#5]
```
Added Set and Map monoid instances in 
http://code.google.com/r/mauricioscheffer-fsharp-typeclasses/source/detail?r=22a
e902606e579e68bc10b0a02b1d6384dedbb7f (don't know how to do a pull request 
here).

Anyway, just my way of saying hi :)
```

Original issue reported on code.google.com by `mauricio...@gmail.com` on 8 Nov 2012 at 12:20

**Comment by SteveGilham** [comment]
Tracked down the change and committed id as https://github.com/SteveGilham/fsharp-typeclasses/commit/8c2bbc5ec93e46b13177e3b8d21465f08fe8ac1c
