### ISSUE TITLE
Add a link to related project

### ISSUE THREAD

**Issue by gusty** [SteveGilham/fsharp-typeclasses#6]
Hi,

Nice to see this project, I started long time ago, now here in github, thanks for migrating it.
I think it worths noting that this experimental project inspired a lot of what is now [FSharpPlus (F#+)](https://github.com/gusty/FSharpPlus) and it still contains contains sample code from this project and a Haskell compatibility module.

Maybe you can add a link in the readme?

Thanks

Gustavo

**Comment by SteveGilham** [comment]
Belatedly, noticed that this issue had been added to what the import process had added to the project.

Should be good now, I hope.

**Comment by gusty** [comment]
Thanks !

**Comment by gusty** [comment]
Off topic, how did you migrate this project from google code?
Is there a feature here in Github to do so?
I would like to move an old project I have in google code before they shut down completely.

**Comment by SteveGilham** [comment]
It's provided at the Google end -- if you go to the project source on the
Google code archive e.g.
https://code.google.com/archive/p/fsharp-typeclasses/source/default/source
then there should be a big "Export to GitHub" button to the right of the
project title.

**Comment by gusty** [comment]
ups, too late 

```
The Google Code project export tool is no longer available
```
Thanks anyway !

**Comment by SteveGilham** [comment]
The raw download link still seems to be working.  You've lost history, but you do get the latest code as a .zip
![download](https://user-images.githubusercontent.com/7460854/36413725-8b3d24e2-1617-11e8-840f-d180b89ce35e.png)

**Comment by gusty** [comment]
Thanks, I have the latest source in anycase, but yes, it seems the history is lost.
So I should go to my old computer and see if I still have a svn repo there.
